export interface PasskeyCredential {
  id: string;
  rawId: string;
  response: {
    clientDataJSON: string;
    attestationObject: string;
  };
  type: 'public-key';
  authenticatorAttachment?: string;
  clientExtensionResults: Record<string, any>;
  /** The extracted public key bytes formatted for the Stellar contract signer */
  publicKeyBytes?: Uint8Array; 
}

export interface PasskeyAssertion {
  id: string;
  rawId: string;
  response: {
    authenticatorData: string;
    clientDataJSON: string;
    signature: string;
    userHandle?: string;
  };
  type: 'public-key';
  clientExtensionResults: Record<string, any>;
  /** The Stellar transaction XDR with the assertion attached as a signature */
  signedXdr?: string;
}

export interface PasskeyRegistrationOptions {
  /** The challenge generated by the relying party / relay */
  challenge: string;
  /** Relying party information */
  rp: {
    name: string;
    id: string;
  };
  /** User information */
  user: {
    id: string;
    name: string;
    displayName: string;
  };
  pubKeyCredParams?: Array<{ type: 'public-key'; alg: number }>;
  timeout?: number;
  authenticatorSelection?: {
    authenticatorAttachment?: 'platform' | 'cross-platform';
    requireResidentKey?: boolean;
    residentKey?: 'discouraged' | 'preferred' | 'required';
    userVerification?: 'required' | 'preferred' | 'discouraged';
  };
  attestation?: 'none' | 'indirect' | 'direct' | 'enterprise';
}

export interface PasskeySignOptions {
  /** The challenge (which should be the hash of the Stellar transaction) */
  challenge: string;
  /** The credential ID to authenticate with */
  credentialId: string;
  timeout?: number;
  userVerification?: 'required' | 'preferred' | 'discouraged';
  rpId?: string;
}

export interface PasskeyProvider {
  createCredential(options: PasskeyRegistrationOptions): Promise<PasskeyCredential>;
  signTransaction(xdr: string, options: PasskeySignOptions): Promise<PasskeyAssertion>;
}
