export interface PasskeyCredential {
  /** base64url credential id — used as the on-chain signer key. */
  id: string;
  rawId: string;
  response: {
    clientDataJSON: string;
    attestationObject: string;
  };
  type: 'public-key';
  authenticatorAttachment?: string;
  clientExtensionResults: Record<string, any>;
  /** Uncompressed P-256 public key (0x04 || X || Y, 65 bytes) registered in the wallet contract. */
  publicKeyBytes: Uint8Array;
}

export interface PasskeyAssertion {
  id: string;
  rawId: string;
  response: {
    /** base64url */
    authenticatorData: string;
    /** base64url */
    clientDataJSON: string;
    /** base64url, DER-encoded ECDSA signature (WebAuthn standard) */
    signature: string;
    userHandle?: string;
  };
  type: 'public-key';
  clientExtensionResults: Record<string, any>;
}

export interface PasskeyRegistrationOptions {
  /** The challenge generated by the relying party / relay */
  challenge: string;
  rp: { name: string; id: string };
  user: { id: string; name: string; displayName: string };
  pubKeyCredParams?: Array<{ type: 'public-key'; alg: number }>;
  timeout?: number;
  authenticatorSelection?: {
    authenticatorAttachment?: 'platform' | 'cross-platform';
    requireResidentKey?: boolean;
    residentKey?: 'discouraged' | 'preferred' | 'required';
    userVerification?: 'required' | 'preferred' | 'discouraged';
  };
  attestation?: 'none' | 'indirect' | 'direct' | 'enterprise';
}

export interface PasskeyAssertionOptions {
  /**
   * base64url challenge. For on-chain authorisation this is the Soroban
   * signature payload hash — the wallet contract checks that clientDataJSON
   * carries exactly this value.
   */
  challenge: string;
  /** Restrict to this credential; omit for discoverable sign-in. */
  credentialId?: string;
  rpId?: string;
  timeout?: number;
  userVerification?: 'required' | 'preferred' | 'discouraged';
}

/** @deprecated use PasskeyAssertionOptions */
export type PasskeySignOptions = PasskeyAssertionOptions & { credentialId: string };

/**
 * Platform seam. The browser implementation lives in this package; React
 * Native supplies its own (react-native-passkeys). Both return the standard
 * WebAuthn JSON shapes; the SDK does all Stellar-specific work on top.
 */
export interface PasskeyProvider {
  createCredential(options: PasskeyRegistrationOptions): Promise<PasskeyCredential>;
  getAssertion(options: PasskeyAssertionOptions): Promise<PasskeyAssertion>;
}
